baseURL = "https://ida-mdc.github.io/workshop-visualization"
languageCode = "en-us"
title = "3D Data Visualization Workshop"
[markup.goldmark.renderer]
unsafe= true
canonifyURLs= true
[params.mermaid]
enable = true
[params.plantuml]
enable = true
[markup]
  [markup.highlight]
      guessSyntax = "false"